AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20
    Environment:
      Variables:
        TODO_TABLE: todo

Resources:
  TodoReader:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LearnDynamoDBApp
      Handler: kryz.handlers.TodoReader::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: todo
      Events:
        ReadTodoItem:
          Type: Api
          Properties:
            Path: /todo/{id}/{username}
            Method: GET
